# Generated by Django 5.2.4 on 2025-09-03 13:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=100)),
                ('education_office', models.CharField(max_length=100)),
                ('subject_category', models.CharField(max_length=50)),
                ('standard_price', models.PositiveIntegerField()),
                ('tuition_fee', models.PositiveIntegerField(help_text='총 교습비(원)')),
                ('lessons_per_week', models.PositiveIntegerField(help_text='주당 수업 횟수')),
                ('lessons_per_month', models.DecimalField(decimal_places=1, help_text='월간 수업 횟수 (소수점 1자리 허용)', max_digits=4)),
                ('minutes_per_class', models.PositiveIntegerField(help_text='1회 수업 시간(분)')),
                ('effective_date', models.DateField(auto_now=True)),
                ('source_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalRegionStandard',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('region_code', models.CharField(max_length=100)),
                ('education_office', models.CharField(max_length=100)),
                ('subject_category', models.CharField(max_length=50)),
                ('standard_price', models.PositiveIntegerField()),
                ('tuition_fee', models.PositiveIntegerField(help_text='총 교습비(원)')),
                ('lessons_per_week', models.PositiveIntegerField(help_text='주당 수업 횟수')),
                ('lessons_per_month', models.DecimalField(decimal_places=1, help_text='월간 수업 횟수 (소수점 1자리 허용)', max_digits=4)),
                ('minutes_per_class', models.PositiveIntegerField(help_text='1회 수업 시간(분)')),
                ('effective_date', models.DateField(blank=True, editable=False)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical region standard',
                'verbose_name_plural': 'historical region standards',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CalculationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('minutes_per_class', models.PositiveIntegerField()),
                ('months', models.PositiveIntegerField()),
                ('lessons_per_month', models.PositiveIntegerField()),
                ('tuition_fee', models.PositiveIntegerField(help_text='총 교습비(원)')),
                ('total_minutes', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('standard_price_at_calc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
                ('region_standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='myapp.regionstandard')),
            ],
        ),
    ]
