# Generated by Django 5.2.4 on 2025-08-14 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=100)),
                ('education_office', models.CharField(max_length=100)),
                ('course_type', models.CharField(max_length=50)),
                ('subject_category', models.CharField(max_length=50)),
                ('standard_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('source_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalculationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('minutes_per_class', models.PositiveIntegerField()),
                ('months', models.PositiveIntegerField()),
                ('lessons_per_month', models.PositiveIntegerField()),
                ('tuition_fee', models.PositiveIntegerField(help_text='총 교습비(원)')),
                ('total_minutes', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('standard_price_at_calc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
                ('region_standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='myapp.regionstandard')),
            ],
        ),
    ]
